# Generated by Django 2.1.3 on 2019-01-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='passcritearia',
            new_name='pass_criteria',
        ),
    ]
