# Generated by Django 2.1.3 on 2019-01-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0002_auto_20190117_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_plan_pic_path',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
