# Generated by Django 2.1.3 on 2019-02-25 05:58

import TestCase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0004_auto_20190122_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_plan_pic_path',
            field=models.FileField(blank=True, null=True, upload_to='upload'), #TestCase.models.test_plan_pic_path
        ),
    ]
