# Generated by Django 2.1.3 on 2019-02-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0005_auto_20190225_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_plan_pic_path',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
    ]
