# Generated by Django 2.1.3 on 2019-03-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0006_auto_20190225_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_note',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='testcase',
            name='case_status',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
