# Generated by Django 2.1.3 on 2020-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0009_auto_20190828_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_prepare',
            field=models.TextField(blank=True, null=True),
        ),
    ]
