# Generated by Django 2.1.3 on 2020-10-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0010_sheet_sheet_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='attend_time',
            field=models.CharField(default='0', max_length=128, null=True, verbose_name='attend_time'),
        ),
    ]
