# Generated by Django 2.1.3 on 2020-12-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0011_sheet_attend_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sorting',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
