# Generated by Django 2.1.3 on 2020-12-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0012_sheet_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='unattend_time',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='attend_time',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
