# Generated by Django 2.1.3 on 2020-12-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0013_auto_20201208_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='Commercial',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='Consumer',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='dvt',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='evt',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
