# Generated by Django 2.1.3 on 2019-01-16 05:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('team_leader', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=32, null=True)),
                ('job_name', models.CharField(max_length=24, null=True)),
                ('gender', models.CharField(max_length=8, null=True)),
                ('avatar', models.FileField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像')),
                ('shot_number', models.CharField(max_length=11, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('university', models.CharField(max_length=255, null=True)),
                ('major', models.CharField(max_length=255, null=True)),
                ('join_in_time', models.DateField(null=True)),
                ('leave_time', models.DateField(null=True)),
                ('belone_to_team', models.ForeignKey(null=True, on_delete=None, to='UserProfile.Team')),
                ('role', models.ForeignKey(null=True, on_delete=None, to='UserProfile.Role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
