# Generated by Django 2.1.3 on 2019-02-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='media/upload/favicon.ico', upload_to='media/upload', verbose_name='头像'),
        ),
    ]
