# Generated by Django 2.1.3 on 2019-08-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_auto_20190808_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='UserProfile.Permission'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='join_in_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='leave_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(blank=True, to='UserProfile.Role'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shot_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
