# Generated by Django 2.1.3 on 2019-03-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20190326_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltablecontent',
            name='ControlTable_List_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.ControlTableList'),
        ),
        migrations.AlterField(
            model_name='controltablecontent',
            name='sheet_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TestCase.Sheet'),
        ),
        migrations.AlterField(
            model_name='controltablecontent',
            name='sku_num',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='controltablecontent',
            name='tester',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserInfo'),
        ),
    ]
