# Generated by Django 2.1.3 on 2019-04-02 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20190329_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={},
        ),
        migrations.AddField(
            model_name='testresult',
            name='result_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='control_table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.ControlTableList'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='project',
        ),
    ]
