# Generated by Django 2.1.3 on 2019-04-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_auto_20190402_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test_result',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
