# Generated by Django 2.1.3 on 2019-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20190410_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='control_table',
            new_name='ControlTableList',
        ),
        migrations.AddField(
            model_name='testresult',
            name='sku_num',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
