# Generated by Django 2.1.3 on 2019-04-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_testresult_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltablelist',
            name='stage_sku_qty',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='sku 数量'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='result_remark'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='result_info',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.ProjectInfo'),
        ),
    ]
