# Generated by Django 2.1.3 on 2019-05-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_auto_20190417_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltablelist',
            name='stage_note',
            field=models.CharField(default='', max_length=255, verbose_name='Project_stage'),
        ),
    ]
