# Generated by Django 2.1.3 on 2019-05-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_controltablelist_stage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ControlTableList',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.ControlTableList'),
        ),
        migrations.AddField(
            model_name='issue',
            name='TRID',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='attribute',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='attribute_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='attribute_name'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='bugzilla_id',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='severity'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='solving_type',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='status'),
        ),
    ]
