# Generated by Django 2.1.3 on 2020-08-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_auto_20190514_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltablelist',
            name='OS_Ver',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='OS_Version'),
        ),
        migrations.AddField(
            model_name='controltablelist',
            name='buffer_activity',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='测试buffer'),
        ),
        migrations.AddField(
            model_name='controltablelist',
            name='system_qty',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='测试系统数量'),
        ),
    ]
