# Generated by Django 2.1.3 on 2020-08-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0010_sheet_sheet_prepare'),
        ('Project', '0013_auto_20200803_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='sheet_prepared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_prepared', models.TextField(blank=True, null=True)),
                ('ControlTable_List', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.ControlTableList')),
                ('sheet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TestCase.Sheet')),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_result',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
