# Generated by Django 2.1.3 on 2020-10-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_auto_20200818_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltablelist',
            name='attend_time',
            field=models.CharField(default='0', max_length=128, null=True, verbose_name='attend_time'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='issue',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=2048, null=True, verbose_name='result_remark'),
        ),
    ]
