# Generated by Django 2.1.3 on 2020-12-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20201021_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='dr_vga',
            new_name='dr_vga_AMD_addon',
        ),
        migrations.AddField(
            model_name='controltablelist',
            name='unattend_time',
            field=models.CharField(default='0', max_length=128, null=True, verbose_name='attend_time'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga_AMD_onboard',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='VGA'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga_Intel_onboard',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='VGA'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga_NV_addon',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='VGA'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_platform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='平台'),
        ),
    ]
