# Generated by Django 2.1.3 on 2020-12-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_auto_20201208_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='dr_bt',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='dr_wireless',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_QCA_bt',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='QCA_bt'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_QCA_bt_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='QCA_bt_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_QCA_wireless',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='QCA_wireless'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_QCA_wireless_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='QCA_wireless_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_audio_model',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Audio_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_chipset_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Chipset_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_cr_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='CardReader_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_iamt_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='iAMT_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_intel_bt',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='intel_bt'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_intel_bt_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='intel_bt_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_intel_wireless',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='intel_wireless'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_intel_wireless_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='intel_wireless_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_lan_model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='LAN_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga_AMD_addon_model',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='AMD_addon_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga_AMD_onboard_model',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='AMD_onboard_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga_Intel_onboard_model',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='vga_Intel_onboard_model'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='dr_vga_NV_addon_model',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='NV_addon_model'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='dr_vga_AMD_addon',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='AMD_addon'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='dr_vga_AMD_onboard',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='AMD_onboard'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='dr_vga_Intel_onboard',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='vga_Intel_onboard'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='dr_vga_NV_addon',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='NV_addon'),
        ),
    ]
