# Generated by Django 2.1.3 on 2020-12-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_auto_20201224_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='testplan_version',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='testplan_version'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='testsummary_version',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='testsummary_version'),
        ),
    ]
