# Generated by Django 2.1.3 on 2021-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0021_testresult_test_result_log_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet_prepared',
            name='ControlTable_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet_prepared',
            name='importyn',
            field=models.CharField(blank=True, default='0', max_length=16, null=True),
        ),
    ]
